name: Ubuntu rdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Seu AuthToken do Ngrok'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


      # Runs a single command using the runners shell
      - name: Instalando o dewktop
        run: sudo apt update && sudo apt install ubuntu-desktop 

      # Runs a set of commands using the runners shell
      - name: Instalando ngrok config usuario e xrdp
        run: |
         sudo useradd -m EXPEDITO001 && sudo adduser EXPEDITO001 sudo && echo 'EXPEDITO001:EXPEDITO001' | sudo chpasswd
         wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm64.tgz
         sudo apt install xrdp xfce4
         tar -xvzf ngrok-stable-linux-arm64.tgz
         sudo ./ngrok authtoken "{{env.auth}}\r"
         sudo service xrdp start
         sudo ./ngrok tcp 3389
